<a href="https://colab.research.google.com/github/Johnwaithz/Pytorch_Tutorial/blob/main/Introduction_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
print('Welcome to pytorch')
import torch
import numpy as np
import pandas as pd


Welcome to pytorch


A tensor is a multidimensional matrix of elements similar to numpy arrays but more powerful and flexible

In [9]:
#numpy array
np1 = np.random.rand(3,4)
np1
np1.dtype

dtype('float64')

In [6]:
#Tensor
tensor_2d = torch.randn(2,4)
tensor_2d

tensor([[-0.3668, -0.4071, -1.3866,  0.1051],
        [ 0.2250, -0.4898, -0.8266,  1.6211]])

In [7]:
#Tensor
tensor_3d = torch.randn(2,4,5)
tensor_3d

tensor([[[-0.2990, -0.3771, -0.4468,  0.7142, -0.4290],
         [-0.3570, -0.0853, -0.0486,  1.4829,  3.6056],
         [-0.4743,  0.0455,  1.0955, -1.4841, -0.2059],
         [-1.5197,  0.9559,  0.7712,  0.1512, -1.1106]],

        [[-1.2889, -0.7520, -0.0351,  2.3321,  1.0356],
         [-1.4573, -0.5700,  0.1343, -0.5294,  2.7469],
         [-0.0491, -0.0533, -1.5575, -1.0310,  1.2045],
         [ 0.4028, -1.0837, -0.3958,  2.6911, -0.3505]]])

In [8]:
#Create a tensor from numpy array
tensor_np = torch.tensor(np1)
tensor_np

tensor([[0.4431, 0.4560, 0.1791, 0.4434],
        [0.8913, 0.8232, 0.6503, 0.1347],
        [0.0387, 0.2612, 0.5599, 0.3884]], dtype=torch.float64)