<a href="https://colab.research.google.com/github/Johnwaithz/Pytorch_Tutorial/blob/main/Tensor_maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
tensor_a = torch.tensor([1,2,3,4,5])
tensor_b = torch.tensor([6,7,8,9,10])

In [4]:
#Addition
tensor_a + tensor_b

tensor([ 7,  9, 11, 13, 15])

In [5]:
#Add function
torch.add(tensor_a, tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [6]:
#Subtraction
tensor_a - tensor_b

tensor([-5, -5, -5, -5, -5])

In [7]:
#Sub function
torch.sub(tensor_a, tensor_b)

tensor([-5, -5, -5, -5, -5])

In [8]:
#Multiplication
tensor_a * tensor_b


tensor([ 6, 14, 24, 36, 50])

In [9]:
#Mul function
torch.mul(tensor_a, tensor_b)

tensor([ 6, 14, 24, 36, 50])

In [10]:
#division
tensor_a / tensor_b

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [11]:
#Div function
torch.div(tensor_a, tensor_b)

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])

In [13]:
#Remainder Modulus
tensor_b % tensor_a

tensor([0, 1, 2, 1, 0])

In [15]:
#remainder function
torch.remainder(tensor_b, tensor_a)

tensor([0, 1, 2, 1, 0])

In [16]:
#Exponents and power
torch.pow(tensor_a, tensor_b)

tensor([      1,     128,    6561,  262144, 9765625])

In [17]:
#Another way to write long hand
tensor_a.add(tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [21]:
#Reassignment
tensor_c = tensor_a.add_(tensor_b)
tensor_c

tensor([25, 30, 35, 40, 45])

In [22]:
#or
tensor_a += tensor_b
tensor_a

tensor([31, 37, 43, 49, 55])

In [24]:
#or
tensor_a = tensor_a + tensor_b
tensor_a

tensor([43, 51, 59, 67, 75])