<a href="https://colab.research.google.com/github/Johnwaithz/Pytorch_Tutorial/blob/main/tensors_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Reshape and view
my_torch = my_torch.reshape(2,5)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
#reshape if we dont know then number of items using -1
my_torch2 = torch.arange(10)
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
#View
my_torch3 = my_torch.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Basically reshape and view are the same

In [15]:
#Grab a specific item
my_torch8 = torch.arange(10)
my_torch8[5]


tensor(5)

In [16]:
#Grab a specific item
my_torch8[5:7]

tensor([5, 6])

In [17]:
my_torch8 = my_torch8.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [19]:
#Return second column
my_torch8[:,1:]


tensor([[1],
        [3],
        [5],
        [7],
        [9]])